### ISSUE TITLE
fixedtable 更新 data 时会出错

### ISSUE THREAD

**Issue by qqzxingchen** [baifendian/bfd-ui#1]
fixedtable组件，在第一次render的时候，没有错误。但是当为其配置的参数发生变化时，将会报错：
![image](https://cloud.githubusercontent.com/assets/8321444/18827184/124fc9aa-8404-11e6-8444-5f4dc72e321b.png)

**Comment by jiangtl** [comment]
thank @qqzxingchen [https://github.com/baifendian/bfd-ui/commit/7feb78c0b1f4908c922d23ffd60ca0b42b79dba6](url)

**Comment by jiangtl** [comment]
thank @qqzxingchen `7feb78c0b1f4908c922d23ffd60ca0b42b79dba6`

**Comment by jiangtl** [comment]
thank @qqzxingchen [https://github.com/baifendian/bfd-ui/commit/7feb78c0b1f4908c922d23ffd60ca0b42b79dba6](7feb78c)

**Comment by jiangtl** [comment]
thank @qqzxingchen [7feb78c](https://github.com/baifendian/bfd-ui/commit/7feb78c0b1f4908c922d23ffd60ca0b42b79dba6)
