### ISSUE TITLE
selec控件需求

### ISSUE THREAD

**Issue by ldd010101** [baifendian/bfd-ui#8]
1.下拉给配置不自适应选择展示上方或下方，默认展示在下面。
2.select 的handleSelect返回event。

**Comment by jianghai** [comment]
1、第一个问题，如果因父元素 overflow 导致展开层被“截断”，这块打算所有展开层放到 body 节点内，可以解决这个问题
2、返回 event 的目的是什么？新版本会增加选中 option 对应的数据项或者 option 的 props
